server:
  port: 8080
  servlet:

    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/views/
  #      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: min
    password: wjdqhqhdks

mybatis:
  mapper-locations: classpath:mapper/**.xml

  jackson:
    serialization:
      fail-on-empty-beans: false

logging.level:
  org.hibernate.SQL: debug